### ISSUE TITLE
More/Read More tag not working

### ISSUE THREAD

**Issue by VertyyBird** [XjSv/Cooked#65]
**Describe the bug**
The More/Read More tag doesn't work in the Recipe Template field.

**To Reproduce**
1. Go to create a recipe.
2. Using visual editor, click on **Insert Read More Tag**.
3. Put any text or shortcode after the tag.
4. Click **Save Draft** and then **Preview** or **Publish**.
5. See that the text after the Read More tag is not hidden and there is no Read More button to click on.

**Expected behavior**
Expected for the tag to function the same as in normal posts, hiding any content contained after the tag.

**Screenshots**
Visual editor view
![image_2024-10-05_135117291](https://github.com/user-attachments/assets/e2291e90-9b01-4ae6-af2e-5021a93aa0fe)

Code editor view
![image_2024-10-05_135250283](https://github.com/user-attachments/assets/08eeabb2-1518-4064-b051-a5250044b0dd)

Recipe post page
![image_2024-10-05_135331800](https://github.com/user-attachments/assets/830204ab-58b2-4fbc-8c97-5ff07675e3d9)

Inspect Element view of recipe page
![image](https://github.com/user-attachments/assets/9880de3f-1824-4ac8-8dbc-fa479d046062)

**Information (please complete the following information):**
 - WordPress Version 6.6.2
 - Plugin Version 1.8.7

**Additional context**
Fresh install of WordPress, no other plugins active.

**Comment by XjSv** [comment]
I am not 100% sure on how this is suppose to work but if I understand the documentation correctly here: https://wordpress.com/support/wordpress-editor/blocks/more-block/#add-the-more-tag-in-the-classic-editor,

The More/Read More tag allows you to make a part of the post show up as an excerpt or summary in the homepage, archive pages, and in subscriber emails. 

Because recipes have their own custom Recipe Excerpt field, this is really not necessary. You can just use the Recipe Excerpt field directly where ever you need it (such as in an Elementor template).

You also mentioned hiding content after the read more tag, but I'm not sure how to get this to work even with a regular post or page. Perhaps you are referring to this option:

> When you toggle on the option to “Hide the excerpt on the full content page“, all the text that’s above the More block in your post will not appear once the reader clicks the “Read more” link to view the full post.
> Toggle the option to " Hide the excerpt on the full content page" within the More block settings.

![image](https://github.com/user-attachments/assets/f0ae8fae-ce16-49ce-83fd-b74abf759a11)

**Comment by VertyyBird** [comment]
Oh, whoops. I missed that when I was reading the WP documentation. I was under the belief that it acted like a "click this button to read the rest of the article" kinda thing. My intended use was to have it hide the Nutrition Facts behind the button since some of my readers are sensitive to seeing that kind of thing. I'll look at some other plugins to see if there's one that can do that.

**Comment by XjSv** [comment]
I think you can achieve this in the theme that you are using. In theory, you can make a template in your theme to override the `cp_recipe` single post type and display it any way you want.

You can also choose to display the individual shortcodes in separate Elementor containers as some users have done.
